name: Continuous Integration
on: [push, pull_request]
jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    env:
      JWT_SECRET: "test-secret"
      DATABASE_URL: "postgresql://user:pass@localhost:5432/test"
      CLIENT_URL: "http://localhost:3000"
      STRIPE_SECRET_KEY: "sk_test_xxx"
      STRIPE_WEBHOOK_SECRET: "whsec_xxx"
      APP_URL: "http://localhost:3000"
      REDIS_URL: "redis://localhost:6379"
      BUCKET_NAME: "bucket-name"
      BUCKET_REGION: "eu-west-1"
      AWS_ACCESS_KEY_ID: "your aws access key id"
      AWS_SECRET_ACCESS_KEY: "your aws secret access key"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: npm install

      - name: Runs Prisma generate
        run: npx prisma generate

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm test
